/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.polancomedia.amplitude;

import com.amplitude.api.Amplitude;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.json.JSONObject;

@Kroll.module(name="Android", id="com.polancomedia.amplitude")
public class AndroidModule extends KrollModule
{

	// Standard Debugging variables
	private static final String TAG = "AmplitudeModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public AndroidModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public void initialize(String token)
	{
		Log.d(TAG, "calling initialize");
		//Amplitude.initialize(TiApplication.getInstance(), token);
		Amplitude.initialize(getActivity(), token);
	}
	
	@Kroll.method
	public void setUserId(String userId)
	{
		Log.d(TAG, "setting userId");
		Amplitude.setUserId(userId);
	}
	
	@Kroll.method
	public void logEvent(String event)
	{
		Log.d(TAG, "logging event");
		Amplitude.logEvent(event);
	}
	
	@Kroll.method
	public String example()
	{
		Log.d(TAG, "example called");
		return "hello world";
	}
	
	// Properties
	@Kroll.getProperty
	public String getExampleProp()
	{
		Log.d(TAG, "get example property");
		return "hello world";
	}
	
	
	@Kroll.setProperty
	public void setExampleProp(String value) {
		Log.d(TAG, "set example property: " + value);
	}

}

